//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminCredential
    {
        public System.Guid AdminCredentialsId { get; set; }
        public Nullable<System.Guid> TenantId { get; set; }
        public byte[] UserName { get; set; }
        public string Password { get; set; }
        public System.Guid AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool Status { get; set; }
    
        public virtual TenantDetail TenantDetail { get; set; }
    }
}
