//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminScope
    {
        public AdminScope()
        {
            this.AdminDetails = new HashSet<AdminDetail>();
        }
    
        public System.Guid AdminScope_Id { get; set; }
        public string AdminScope_Name { get; set; }
        public string AdminScope_Description { get; set; }
        public System.DateTime AdminScope_AddedOn { get; set; }
        public System.Guid AdminScope_AddedBy { get; set; }
        public Nullable<System.DateTime> AdminScope_UpdatedOn { get; set; }
        public Nullable<System.Guid> AdminScope_UpdatedBy { get; set; }
        public bool AdminScope_Status { get; set; }
    
        public virtual ICollection<AdminDetail> AdminDetails { get; set; }
    }
}
