//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantDetail
    {
        public TenantDetail()
        {
            this.AdminCredentials = new HashSet<AdminCredential>();
            this.TenantAddresses = new HashSet<TenantAddress>();
        }
    
        public System.Guid TenantDetails_Id { get; set; }
        public string TenantDetails_Name { get; set; }
        public string TenantDetails_Description { get; set; }
        public string TenantDetails_TenantSite { get; set; }
        public string TenantDetails_TenantUrl { get; set; }
        public System.DateTime TenantDetails_AddedOn { get; set; }
        public System.Guid TenantDetails_AddedBy { get; set; }
        public Nullable<System.DateTime> TenantDetails_UpdatedOn { get; set; }
        public Nullable<System.Guid> TenantDetails_UpdatedBy { get; set; }
        public bool TenantDetails_Status { get; set; }
    
        public virtual ICollection<AdminCredential> AdminCredentials { get; set; }
        public virtual ICollection<TenantAddress> TenantAddresses { get; set; }
    }
}
